name: ci

on: [push, pull_request]

jobs:
  build:
    runs-on: macOS-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.2.4
        with:
          version: 7
        
      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          
      - name: Cache node modules
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: ./node_modules
          key: ${{ runner.os }}-build-cache-node-modules-${{ hashFiles('**/package.json') }}
          restore-keys: |
            cache-node-modules-

      - name: Run ci
        run: |
          pnpm install
          pnpm run ci
